### ISSUE TITLE
Error when running ansible-playbook

### ISSUE THREAD

**Issue by evancorl** [poetic/nebula#6]
When I cloned the repo and ran `vagrant up`, I got this error message:

```
    default: Running ansible-playbook...
ERROR: package is not a legal parameter in an Ansible task or handler
Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

To proceed without errors, I removed `nebula` from the listed roles in `nebula/.nebula/ansible/playbook.yml`:

```

---
- hosts: all
  become: yes

  vars_files:
    - vars/main.yml

  roles:
    - geerlingguy.git
    - nebula
    - geerlingguy.postfix
    - geerlingguy.apache
    - geerlingguy.mysql
    - geerlingguy.php
    - geerlingguy.php-pecl
    - geerlingguy.php-mysql
    - geerlingguy.composer
    - geerlingguy.drush
    - geerlingguy.drupal-console
```

Does the `nebula/.nebula/ansible/roles/nebula` folder need a `.travis.yml` file? The rest of the role folders have one.
